/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard.enquiries'
import { Route as DashboardListingsIndexRouteImport } from './routes/dashboard.listings.index'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard.listings.new'
import { Route as DashboardListingsIdEditRouteImport } from './routes/dashboard.listings.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsIndexRoute = DashboardListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsIdEditRoute = DashboardListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/dashboard/listings/$id/edit': typeof DashboardListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/dashboard/listings': typeof DashboardListingsIndexRoute
  '/dashboard/listings/$id/edit': typeof DashboardListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/listings/$id': typeof ListingsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/dashboard/listings/': typeof DashboardListingsIndexRoute
  '/dashboard/listings/$id/edit': typeof DashboardListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/listings'
    | '/login'
    | '/dashboard/enquiries'
    | '/listings/$id'
    | '/dashboard/'
    | '/dashboard/listings/new'
    | '/dashboard/listings/'
    | '/dashboard/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/listings'
    | '/login'
    | '/dashboard/enquiries'
    | '/listings/$id'
    | '/dashboard'
    | '/dashboard/listings/new'
    | '/dashboard/listings'
    | '/dashboard/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/listings'
    | '/login'
    | '/dashboard/enquiries'
    | '/listings/$id'
    | '/dashboard/'
    | '/dashboard/listings/new'
    | '/dashboard/listings/'
    | '/dashboard/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings/': {
      id: '/dashboard/listings/'
      path: '/listings'
      fullPath: '/dashboard/listings/'
      preLoaderRoute: typeof DashboardListingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings/new': {
      id: '/dashboard/listings/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings/$id/edit': {
      id: '/dashboard/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/dashboard/listings/$id/edit'
      preLoaderRoute: typeof DashboardListingsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
  DashboardListingsIndexRoute: typeof DashboardListingsIndexRoute
  DashboardListingsIdEditRoute: typeof DashboardListingsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardListingsNewRoute: DashboardListingsNewRoute,
  DashboardListingsIndexRoute: DashboardListingsIndexRoute,
  DashboardListingsIdEditRoute: DashboardListingsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
